version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend-data:/app/data
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - xtracta-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend-data:/app/data
      - backups:/app/data/backups
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
      - DATA_DIR=/app/data
      - ENABLE_BACKUPS=true
      - BACKUP_INTERVAL_HOURS=24
      - BACKUP_DIR=/app/data/backups
    networks:
      - xtracta-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  xtracta-network:
    driver: bridge

volumes:
  frontend-data:
    driver: local
  backend-data:
    driver: local
  backups:
    driver: local 